### PR TITLE
Update tabulate requirement to >=0.8.8,<=0.8.10

### PR DESCRIPTION
**Pull request by chenwany**
### Description of changes
* tabulate 0.8.7 doesn't work well with python3.10
With tabulate version 0.8.7 and python 3.10, pcluster configure doesn't work correctly.
the error with running `pcluster configure` is
```
2022-10-21 14:17:59,236 - INFO - entrypoint.py:226:run() - Handling CLI command configure
2022-10-21 14:17:59,236 - INFO - entrypoint.py:227:run() - Parsed CLI arguments: args(Namespace(operation='configure', region=None, config='/test', func=<bound method ConfigureCommand.execute of <pcluster.cli.commands.configure.command.ConfigureCommand object at 0x105535d20>>, expects_extra_args=False)), extra_args([])
2022-10-21 14:17:59,238 - ERROR - entrypoint.py:256:main() - Unexpected error of type ImportError: cannot import name 'Iterable' from 'collections' (/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)
Traceback (most recent call last):
  File "/Users/chenwany/python310/lib/python3.10/site-packages/pcluster/cli/entrypoint.py", line 234, in main
    ret = run(sys.argv[1:])
  File "/Users/chenwany/python310/lib/python3.10/site-packages/pcluster/cli/entrypoint.py", line 228, in run
    return _run_operation(model, args, extra_args)
  File "/Users/chenwany/python310/lib/python3.10/site-packages/pcluster/cli/entrypoint.py", line 197, in _run_operation
    return args.func(args, extra_args)
  File "/Users/chenwany/python310/lib/python3.10/site-packages/pcluster/cli/commands/configure/command.py", line 36, in execute
    from pcluster.cli.commands.configure.easyconfig import configure
  File "/Users/chenwany/python310/lib/python3.10/site-packages/pcluster/cli/commands/configure/easyconfig.py", line 24, in <module>
    from pcluster.cli.commands.configure.networking import (
  File "/Users/chenwany/python310/lib/python3.10/site-packages/pcluster/cli/commands/configure/networking.py", line 22, in <module>
    from pcluster.cli.commands.configure.utils import handle_client_exception
  File "/Users/chenwany/python310/lib/python3.10/site-packages/pcluster/cli/commands/configure/utils.py", line 18, in <module>
    from tabulate import tabulate
  File "/Users/chenwany/python310/lib/python3.10/site-packages/tabulate.py", line 16, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)
```
* This is fixed in tabulate 0.8.8: https://github.com/astanin/python-tabulate/pull/105
### Tests
* Test with python 3.10 and tabulate 0.8.7 --not ok
* Test with python 3.10 and tabulate 0.8.8 --not ok
* Describe the added/modified tests.

### References
* Link to related PRs in other packages (i.e. cookbook, node).
* Link to documentation useful to understand the changes.

### Checklist
- [ ] Make sure you are pointing to **the right branch** and add a label in the PR title (i.e. **2.x** vs **3.x**)
- [ ] Check all commits' messages are clear, describing what and why vs how.
- [ ] Make sure **to have added unit tests or integration tests** to cover the new/modified code.
- [ ] Check if documentation is impacted by this change.

Please review the [guidelines for contributing](../CONTRIBUTING.md) and [Pull Request Instructions](https://github.com/aws/aws-parallelcluster/wiki/Git-Pull-Request-Instructions).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by francesco-giordano — APPROVED** [review]
LGTM!
