### PR TITLE
Update tabulate requirement from >=0.8.2,<0.8.10 to >=0.8.8,<=0.8.10 

### PR DESCRIPTION
**Pull request by chenwany**
### Description of changes
* Update tabulate requirement from >=0.8.2,<0.8.10 to >=0.8.8,<=0.8.10 
* We have `from tabulate import tabulate` in `aws-parallelcluster/cli/src/pcluster/cli_commands/update.py`, if the tabulate version <0.8.8, the import will fail with the following error in python 3.10: 
`    from tabulate import tabulate
  File "/home/conda/feedstock_root/build_artifacts/aws-parallelcluster_1666319446692/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.10/site-packages/tabulate.py", line 16, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/home/conda/feedstock_root/build_artifacts/aws-parallelcluster_1666319446692/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.10/collections/__init__.py)
`
* This is fixed in tabulate 0.8.8: https://github.com/astanin/python-tabulate/pull/105
* We need to require the version to be larger than 0.8.8 to avoid the fail in python 3.10. Here's the error message from conda build with python 3.10: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=592951&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642
* Update from <0.8.10 to <=0.8.10 because 0.8.10 is released
### Tests
* Describe the automated and/or manual tests executed to validate the patch.
* Describe the added/modified tests.

### References
* Link to related PRs in other packages (i.e. cookbook, node).
* Link to documentation useful to understand the changes.

### Checklist
- [ ] Make sure you are pointing to **the right branch** and add a label in the PR title (i.e. **2.x** vs **3.x**)
- [ ] Check all commits' messages are clear, describing what and why vs how.
- [ ] Make sure **to have added unit tests or integration tests** to cover the new/modified code.
- [ ] Check if documentation is impacted by this change.

Please review the [guidelines for contributing](../CONTRIBUTING.md) and [Pull Request Instructions](https://github.com/aws/aws-parallelcluster/wiki/Git-Pull-Request-Instructions).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: cli/requirements.txt [hunk 1]
```diff
@@ -1,5 +1,5 @@
 boto3>=1.16.14
-tabulate>=0.8.2,<0.8.10
+tabulate>=0.8.8,<=0.8.10
```
Comment (francesco-giordano) [inline cli/requirements.txt:2]: Is there any specific reason to set the 0.8.10 as the last, what about `tabulate>=0.8.8,<0.9`

Comment (chenwany) [reply cli/requirements.txt:2]: In our code, we have the third party licenses for version `0.8.10`
```
https://github.com/aws/aws-parallelcluster/blob/develop/THIRD-PARTY-LICENSES.txt
```
Not sure if the licensing will change after 0.8.10. And we don't have version between 0.8.10 and 0.9 now

**Review by francesco-giordano — APPROVED** [review]
LGTM!
